[package]
name = "chr_decoder"
version = "0.1.0"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[dependencies]
glium = "*"

[dependencies.sdl2]
    git = "https://github.com/AngryLawyer/rust-sdl2"
